name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet requests

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.24.0'

    - name: Build APK
      run: |
        # Ensure we are in the root where main.py is
        # Added MANAGE_EXTERNAL_STORAGE for Android 11+ full file access
        flet build apk --verbose --include-packages flet,requests --permissions android.permission.INTERNET,android.permission.READ_EXTERNAL_STORAGE,android.permission.WRITE_EXTERNAL_STORAGE,android.permission.MANAGE_EXTERNAL_STORAGE

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: python-scanner-app
        path: build/apk/app-release.apk
